export const products = [
  {
    name: "Ichigo's Zanpakuto - Zangetsu Katana",
    description: "Replica of Ichigo Kurosaki’s Zanpakuto from Bleach.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714635/ichigo-zangetsu-1_oldcse.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714649/ichigo-zangetsu-2_bfzvwg.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714641/ichigo-zangetsu-3_u5cb1g.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714645/ichigo-zangetsu-4_vsaotm.webp",
    ],
    productType: "Katana",
    anime: "Bleach",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Rengoku's Nichirin Sword",
    description:
      "Fiery Nichirin sword wielded by Rengoku Kyojuro from Demon Slayer.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714643/Rengoku-nichirin-1_pzgujw.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714645/Rengoku-nichirin-2_o2bmpf.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714647/Rengoku-nichirin-3_bfwgsm.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714646/Rengoku-nichirin-4_pdvvab.webp",
    ],
    productType: "Katana",
    anime: "Demon Slayer",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Tanjiro's Nichirin Sword",
    description:
      "Tanjiro Kamado’s signature black Nichirin blade from Demon Slayer.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714646/tanjiro-nichirin-1_fya1us.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714648/tanjiro-nichirin-2_k7ot0w.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714649/tanjiro-nichirin-3_hrcrhk.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714648/tanjiro-nichirin-4_oraih0.webp",
    ],
    productType: "Katana",
    anime: "Demon Slayer",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Zenitsu's Nichirin Sword",
    description: "Thunder-breathing Nichirin sword of Zenitsu Agatsuma.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714649/zenitsu-nichirin-1_kliwvc.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714653/zenitsu-nichirin-2_detrsk.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714652/zenitsu-nichirin-3_e9nyvm.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714660/zenitsu-nichirin-4_nghklu.webp",
    ],
    productType: "Katana",
    anime: "Demon Slayer",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Zoro's Enma Sword",
    description: "Powerful Enma sword wielded by Roronoa Zoro in One Piece.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714654/zoro-enma-1_pcljr2.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714658/zoro-enma-2_fsdoe0.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714654/zoro-enma-3_xhlduz.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714661/zoro-enma-4_xymbxq.webp",
    ],
    productType: "Katana",
    anime: "One Piece",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Zoro's Shisui Sword",
    description: "Legendary black blade Shisui carried by Roronoa Zoro.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714660/zoro-shisui-1_wopkhq.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714660/zoro-shisui-2_kn4nd9.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714660/zoro-shisui-3_fua3qt.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714666/zoro-shisui-4_wxsdvb.webp",
    ],
    productType: "Katana",
    anime: "One Piece",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },

  // Action Figure
  {
    name: "Byakuya Kuchiki Action Figure",
    description:
      "Detailed action figure of Captain Byakuya Kuchiki from Bleach.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714406/byakuya-1_tuqbcv.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714406/byakuya-2_c3pcdk.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714413/byakuya-3_l2sjys.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714412/byakuya-4_mlwplk.webp",
    ],
    productType: "Action Figure",
    anime: "Bleach",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Ichigo Kurosaki Action Figure",
    description: "Detailed action figure of Ichigo Kurosaki from Bleach.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714422/ichigo-1_yreefb.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714414/ichigo-2_zqyzi9.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714414/ichigo-3_qcmw3r.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714421/ichigo-4_xki2xs.webp",
    ],
    productType: "Action Figure",
    anime: "Bleach",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Rengoku Kishibe Action Figure",
    description: "Detailed action figure of Rengoku Kishibe from Demon Slayer.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714426/rengoku-1_ubdelw.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714427/rengoku-2_nan5hu.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714426/rengoku-3_a0xys1.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714450/rengoku-4_usvc4w.webp",
    ],
    productType: "Action Figure",
    anime: "Demon Slayer",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Tengen Uzui Action Figure",
    description: "Detailed action figure of Tengen Uzui from Demon Slayer.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714448/tengen-1_sw38n2.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714435/tengen-2_qvvpdm.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714439/tengen-3_zuplhx.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714487/tengen-4_k9dbnp.webp",
    ],
    productType: "Action Figure",
    anime: "Demon Slayer",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Yoruichi Action Figure",
    description: "Detailed action figure of Yoruichi from Demon Slayer.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714494/yoruichi-11_y6hstj.jpg",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714495/yoruichi-12_eyugrd.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714512/yoruichi-13_ty0klc.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714582/yoruichi-14_qzvf4b.webp",
    ],
    productType: "Action Figure",
    anime: "Demon Slayer",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Zenitsu Agatsuma Action Figure",
    description:
      "Detailed action figure of Zenitsu Agatsuma from Demon Slayer.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714571/zenitsu-1_vkfp02.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714608/zenitsu-2_zuorw5.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714592/zenitsu-3_hamwrm.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714593/zenitsu-4_rpgba7.webp",
    ],
    productType: "Action Figure",
    anime: "Demon Slayer",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Son Goku Action Figure",
    description: "Detailed action figure of Son Goku from Dragon Ball Z.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714601/goku-1_rakvbj.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714613/goku-2_skjvlk.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714593/goku-3_ic6dem.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714634/goku-4_t6ax1y.webp",
    ],
    productType: "Action Figure",
    anime: "Dragon Ball Z",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Son Goku Action Figure",
    description: "Detailed action figure of Son Goku from Dragon Ball Z.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714641/goku-sprit-bomb-1_qxb5n7.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714623/goku-sprit-bomb-2_m0atiw.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714645/goku-sprit-bomb-3_axsals.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714411/goku-sprit-bomb-4_t6yqkh.webp",
    ],
    productType: "Action Figure",
    anime: "Dragon Ball Z",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Dragon Ball Z Shenron Action Figure",
    description: "Detailed action figure of Shenron from Dragon Ball Z.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714406/shenron-1_h1uesa.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714406/shenron-2_ll5aaq.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714414/shenron-3_nermgj.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714424/shenron-4_eqijh3.webp",
    ],
    productType: "Action Figure",
    anime: "Dragon Ball Z",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Itachi Uchiha Action Figure",
    description: "Detailed action figure of Itachi Uchiha from Naruto.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714421/itachi-11_be4sbz.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714426/itachi-12_mzxijh.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714432/itachi-13_lsmahc.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714488/itachi-14_di2rrn.webp",
    ],
    productType: "Action Figure",
    anime: "Naruto",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Itachi & Sasuke Action Figure",
    description: "Detailed action figure of Itachi & Sasuke from Naruto.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714439/itachi-sasuke-1_vfmhsy.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714447/itachi-sasuke-3_eh9m7g.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714451/itachi-sasuke-2_fmd6mx.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714448/itachi-sasuke-4_flnpyf.webp",
    ],
    productType: "Action Figure",
    anime: "Naruto",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Kakashi Hatake Chibi Action Figure",
    description: "Detailed chibi action figure of Kakashi Hatake from Naruto.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714454/kakashi-chibi-1_jelcsv.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714451/kakashi-chibi-2_mtsipo.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714455/kakashi-chibi-3_forubz.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714453/kakashi-chibi-4_vvb9rb.webp",
    ],
    productType: "Action Figure",
    anime: "Naruto",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Madara Uchiha Six Paths Action Figure",
    description: "Detailed action figure of Madara Uchiha from Naruto.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714463/madara-six-paths-1_ne6fgh.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714464/madara-six-paths-2_uq3rih.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714466/madara-six-paths-3_knowjt.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714472/madara-six-paths-4_sylyru.webp",
    ],
    productType: "Action Figure",
    anime: "Naruto",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Naruto Uzumaki Action Figure",
    description: "Detailed action figure of Naruto Uzumaki from Naruto.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714472/naruto-11_czgkd4.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714467/naruto-12_mhlqbo.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714472/naruto-13_jr8hfo.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714471/naruto-14_nhhz5f.webp",
    ],
    productType: "Action Figure",
    anime: "Naruto",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Portagas D. Ace Action Figure",
    description: "Detailed action figure of Portagas D. Ace from One Piece.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714478/Ace-11_plk9lf.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714479/Ace-12_oyns56.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714488/Ace-13_n5ex9v.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714490/Ace-14_wrynhv.webp",
    ],
    productType: "Action Figure",
    anime: "One Piece",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Crocodile Action Figure",
    description: "Detailed action figure of Crocodile from One Piece.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714541/crocodile-1_ik7xhy.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714518/crocodile-2_xwqdng.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714507/crocodile-3_ujrjw5.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714546/crocodile-4_ptxupq.webp",
    ],
    productType: "Action Figure",
    anime: "One Piece",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Monkey D. Luffy Action Figure",
    description: "Detailed action figure of Monkey D. Luffy from One Piece.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714585/luffy-11_rjnbol.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714584/luffy-12_kmkrwn.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714586/luffy-13_hijkut.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714596/luffy-14_eyt8tk.webp",
    ],
    productType: "Action Figure",
    anime: "One Piece",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Roronoa Zoro Action Figure",
    description: "Detailed action figure of Roronoa Zoro from One Piece.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714623/Zoro-12_bcbwil.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714631/Zoro-13_jdwtcy.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714635/Zoro-14_yi9j8v.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714635/Zoro-11_g6a1vo.webp",
    ],
    productType: "Action Figure",
    anime: "One Piece",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Boa Hancock Action Figure",
    description: "Detailed action figure of Boa Hancock from One Piece.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714518/hancock-1_y1xc2s.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714560/hancock-2_t8zab5.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714569/hancock-3_wolakk.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714577/hancock-4_gfehrk.webp",
    ],
    productType: "Action Figure",
    anime: "One Piece",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
  {
    name: "Monster Trio Chibi Action Figure",
    description:
      "Detailed chibi action figure of Monster Trio - Luffy, Sanji, Zoro from One Piece.",
    images: [
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714601/monster-trio-chibi-1_sn3suv.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714603/monster-trio-chibi-luffy_ggis5x.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714607/monster-trio-chibi-sanji_gluuso.webp",
      "https://res.cloudinary.com/dsxxxxlpf/image/upload/v1756714610/monster-trio-chibi-zoro_a9xc6c.webp",
    ],
    productType: "Action Figure",
    anime: "One Piece",
    price: 120,
    discountedPrice: 140,
    stock: 50,
    averageRating: 1,
    reviews: [],
    popularity: parseInt(Math.random() * 100),
  },
];
